import type { WalletConnectV2ListInfoType } from '@/types'
/**
 * walletconnect v2 默认链接钱包初始列表
 */
export const WalletConnectV2ListInfo: WalletConnectV2ListInfoType[] = [
	{
		id: 'c57ca95b47569778a828d19178114f4db188b89b763c899ba0be274e97267d96',
		name: 'MetaMask',
		homepage: 'https://metamask.io/',
		image_id: '5195e9db-94d8-4579-6f11-ef553be95100',
		order: 10,
		app: {
			browser: null,
			ios: 'https://apps.apple.com/us/app/metamask/id1438144202',
			android: 'https://play.google.com/store/apps/details?id=io.metamask',
			mac: null,
			windows: null,
			linux: null,
			chrome: 'https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn',
			firefox: 'https://addons.mozilla.org/en-US/firefox/addon/ether-metamask/',
			safari: null,
			edge: 'https://microsoftedge.microsoft.com/addons/detail/metamask/ejbalbakoplchlghecdalmeeeajnimhm?hl=en-US',
			opera: 'https://addons.opera.com/en-gb/extensions/details/metamask-10/',
		},
		injected: [{ injected_id: 'isMetaMask', namespace: 'eip155' }],
		mobile: { native: 'metamask://', universal: 'https://metamask.app.link' },
		desktop: { native: null, universal: '' },
		imageName: 'metamask',
	},
	{
		id: '971e689d0a5be527bac79629b4ee9b925e82208e5168b733496a09c0faed0709',
		name: 'OKX Wallet',
		homepage: 'https://www.okx.com/web3',
		image_id: '45f2f08e-fc0c-4d62-3e63-404e72170500',
		order: 4130,
		app: {
			browser: 'https://www.okx.com/download',
			ios: 'https://apps.apple.com/us/app/okx-buy-bitcoin-eth-crypto/id1327268470',
			android: 'https://play.google.com/store/apps/details?id=com.okinc.okex.gp',
			mac: 'https://www.okx.com/download',
			windows: 'https://www.okx.com/download',
			linux: 'https://www.okx.com/download',
			chrome: null,
			firefox: null,
			safari: null,
			edge: null,
			opera: null,
		},
		injected: null,
		mobile: { native: 'okex://main', universal: '' },
		desktop: { native: '', universal: null },
		imageName: 'okeWallet',
	},
	{
		id: '38f5d18bd8522c244bdd70cb4a68e0e718865155811c043f052fb9f1c51de662',
		name: 'BitKeep',
		homepage: 'https://bitkeep.com',
		image_id: '3f7075d0-4ab7-4db5-404d-3e4c05e6fe00',
		order: 190,
		app: {
			browser: 'https://bitkeep.com',
			ios: 'https://bitkeep.com/download',
			android: 'https://bitkeep.com/download',
			mac: null,
			windows: null,
			linux: null,
			chrome: 'https://chrome.google.com/webstore/detail/bitkeep-crypto-nft-wallet/jiidiaalihmmhddjgbnbgdfflelocpak',
			firefox: null,
			safari: null,
			edge: null,
			opera: null,
		},
		injected: [{ injected_id: 'isBitKeep', namespace: 'eip155' }],
		mobile: { native: 'bitkeep://', universal: 'https://bkapp.vip' },
		desktop: { native: '', universal: '' },
		imageName: 'bitkeep',
	},
	{
		id: 'ef333840daf915aafdc4a004525502d6d49d77bd9c65e0642dbaefb3c2893bef',
		name: 'imToken',
		homepage: 'https://token.im/',
		image_id: '99520548-525c-49d7-fb2f-5db65293b000',
		order: 70,
		app: {
			browser: 'https://token.im/',
			ios: 'https://apps.apple.com/us/app/imtoken2/id1384798940',
			android: 'https://play.google.com/store/apps/details?id=im.token.app',
			mac: '',
			windows: '',
			linux: '',
			chrome: null,
			firefox: null,
			safari: null,
			edge: null,
			opera: null,
		},
		injected: null,
		mobile: { native: 'imtokenv2://', universal: '' },
		desktop: { native: '', universal: '' },
		imageName: 'imtoken',
	},
	{
		id: '4622a2b2d6af1c9844944291e5e7351a6aa24cd7b23099efac1b2fd875da31a0',
		name: 'Trust Wallet',
		homepage: 'https://trustwallet.com/',
		image_id: '0528ee7e-16d1-4089-21e3-bbfb41933100',
		order: 20,
		app: {
			browser: null,
			ios: 'https://apps.apple.com/app/apple-store/id1288339409',
			android: 'https://play.google.com/store/apps/details?id=com.wallet.crypto.trustapp',
			mac: null,
			windows: null,
			linux: null,
			chrome: 'https://chrome.google.com/webstore/detail/trust-wallet/egjidjbpglichdcondbcbdnbeeppgdph',
			firefox: null,
			safari: null,
			edge: null,
			opera: null,
		},
		injected: [
			{ injected_id: 'isTrust', namespace: 'eip155' },
			{ injected_id: 'isTrustWallet', namespace: 'eip155' },
		],
		mobile: { native: 'trust://', universal: 'https://link.trustwallet.com' },
		desktop: { native: null, universal: null },
		imageName: 'trustwallet',
	},
	{
		id: '20459438007b75f4f4acb98bf29aa3b800550309646d375da5fd4aac6c2a2c66',
		name: 'TokenPocket',
		homepage: 'https://tokenpocket.pro/',
		image_id: 'f3119826-4ef5-4d31-4789-d4ae5c18e400',
		order: 140,
		app: {
			browser: 'https://chrome.google.com/webstore/detail/tokenpocket/mfgccjchihfkkindfppnaooecgfneiii',
			ios: 'https://apps.apple.com/us/app/tp-wallet/id6444625622?l=en',
			android: 'https://play.google.com/store/apps/details?id=vip.mytokenpocket',
			mac: null,
			windows: null,
			linux: null,
			chrome: 'https://chrome.google.com/webstore/detail/tokenpocket/mfgccjchihfkkindfppnaooecgfneiii',
			firefox: null,
			safari: null,
			edge: null,
			opera: null,
		},
		injected: [{ injected_id: 'isTokenPocket', namespace: 'eip155' }],
		mobile: { native: 'tpoutside://', universal: null },
		desktop: { native: null, universal: null },
		imageName: 'tokenPocket',
	},
	{
		id: 'ecc4036f814562b41a5268adc86270fba1365471402006302e70169465b7ac18',
		name: 'Zerion',
		homepage: 'https://zerion.io/',
		image_id: 'f216b371-96cf-409a-9d88-296392b85800',
		order: 60,
		app: {
			browser: 'https://app.zerion.io',
			ios: 'https://apps.apple.com/app/id1456732565',
			android: 'https://play.google.com/store/apps/details?id=io.zerion.android&hl=en&gl=US',
			mac: 'https://apps.apple.com/app/id1456732565',
			windows: '',
			linux: '',
			chrome: null,
			firefox: null,
			safari: null,
			edge: null,
			opera: null,
		},
		injected: null,
		mobile: { native: 'zerion://', universal: 'https://wallet.zerion.io' },
		desktop: { native: 'zerion://', universal: 'https://wallet.zerion.io' },
		imageName: 'zerion',
	},
]
